plugin:
   prefix: '&b[CustomItems] &r'
   resource-pack: 'null'
   ##If set from false to true please reload/restart your server because the plugin can't have all the recipes in his memory
   remove-all-vanilla-recipes: false
   ##Check for updates if an player joins with permission customitems.update (you could also use the /ci update command)
   update-check: true
   ##If set to false you will not longer get the messages "no update available" if you join the server
   no-update-available-message-on-join: false